# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время и дата создания')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID пользователя')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Никнейм')),
                ('access_token', models.CharField(max_length=200, verbose_name='Токен')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
