# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время и дата создания')),
                ('text', models.CharField(max_length=30, verbose_name='Текст')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_list', to='core.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'хэштэги',
                'verbose_name': 'хэштэг',
            },
        ),
    ]
