# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_club_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='Public',
        ),
    ]
