# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161106_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время и дата создания')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_list', to='core.User', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'координата',
                'verbose_name_plural': 'координаты',
            },
        ),
    ]
