# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161106_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=20, verbose_name='Долгота'),
        ),
    ]
