# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coordinate_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Токен'),
        ),
    ]
