# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161106_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=100, verbose_name='ID поста'),
        ),
    ]
