# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Время и дата создания')),
                ('owner_id', models.BigIntegerField(verbose_name='ID паблика')),
            ],
            options={
                'verbose_name': 'паблик',
                'verbose_name_plural': 'паблики',
            },
        ),
    ]
