# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
