# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161029_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='User',
        ),
        migrations.AddField(
            model_name='public',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='public_list', to='core.User', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
